param(
    [string]$Python = "python",
    [string]$Output = ".\constraints\windows-release.txt"
)

$ErrorActionPreference = "Stop"
Set-Location (Split-Path -Parent $PSScriptRoot)

function Invoke-Native {
    param(
        [Parameter(Mandatory = $true)][string]$FilePath,
        [Parameter(ValueFromRemainingArguments = $true)][string[]]$Arguments
    )

    & $FilePath @Arguments
    if ($LASTEXITCODE -ne 0) {
        throw "Commande native échouée ($LASTEXITCODE) : $FilePath $($Arguments -join ' ')"
    }
}

$Version = (& $Python -c "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}')").Trim()
if ($LASTEXITCODE -ne 0 -or $Version -ne "3.12") {
    throw "La génération des contraintes exige Python 3.12 exactement (détecté : $Version)."
}

$TempRoot = Join-Path $env:TEMP ("ssr-python-constraints-" + [guid]::NewGuid().ToString("N"))
try {
    Invoke-Native $Python -m venv $TempRoot
    $ResolverPython = Join-Path $TempRoot "Scripts\python.exe"

    Invoke-Native $ResolverPython -m pip install --disable-pip-version-check "pip==26.2.1"
    Invoke-Native $ResolverPython -m pip install --disable-pip-version-check "setuptools>=75" wheel
    Invoke-Native $ResolverPython -m pip install --disable-pip-version-check -e ".[all]"

    $Resolved = & $ResolverPython -m pip freeze --all --exclude-editable
    if ($LASTEXITCODE -ne 0) {
        throw "Impossible de figer les dépendances résolues."
    }

    $Packages = @(
        $Resolved |
            Where-Object {
                $_ -and
                $_ -notmatch "^pip==" -and
                $_ -notmatch "^stream-state-router=="
            } |
            Sort-Object { $_.ToLowerInvariant() }
    )

    $Target = Join-Path $PWD $Output
    $Directory = Split-Path -Parent $Target
    New-Item -ItemType Directory -Force -Path $Directory | Out-Null

    $Header = @(
        "# Generated by scripts/refresh_python_constraints.ps1",
        "# Target: Windows x64 / Python 3.12",
        "# Source of direct dependency intent: pyproject.toml",
        "# Do not edit package versions manually; regenerate and review the diff.",
        ""
    )
    @($Header + $Packages) | Set-Content -Path $Target -Encoding utf8
    Write-Host "Contraintes Python régénérées : $Target" -ForegroundColor Green
}
finally {
    if (Test-Path $TempRoot) {
        Remove-Item $TempRoot -Recurse -Force -ErrorAction SilentlyContinue
    }
}
