from __future__ import annotations

from typing import Protocol

from .models import MediaState


class MediaProvider(Protocol):
    """Provider contract used by SSR; concrete players remain replaceable."""

    @property
    def name(self) -> str: ...

    @property
    def capabilities(self) -> tuple[str, ...]: ...

    def state(self) -> MediaState: ...

    def artwork(self) -> tuple[bytes, str]: ...

    def play(self) -> None: ...

    def pause(self) -> None: ...

    def stop(self) -> None: ...

    def next(self) -> None: ...

    def previous(self) -> None: ...

    def seek(self, seconds: float) -> None: ...

    def set_volume(self, percent: float) -> None: ...

    def play_uri(self, uri: str) -> None: ...

    def enqueue_uri(self, uri: str) -> None: ...

    def clear_queue(self) -> None: ...
